# Generated by Django 4.2.23 on 2025-08-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_mycontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
