# Generated by Django 4.2.23 on 2025-08-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('booked', 'Booked'), ('declined', 'Declined'), ('timed out', 'Timed Out')], default='waiting', max_length=25),
        ),
    ]
