# Generated by Django 3.2.20 on 2023-08-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealOption',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('meal_category', models.IntegerField(choices=[(0, 'Starters'), (1, 'Mains'), (2, 'Desserts'), (3, 'New')], default=3)),
                ('available', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-meal_category'],
            },
        ),
        migrations.CreateModel(
            name='Milkshake',
            fields=[
                ('beverage_id', models.AutoField(primary_key=True, serialize=False)),
                ('beverage_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('available', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Smoothie',
            fields=[
                ('beverage_id', models.AutoField(primary_key=True, serialize=False)),
                ('beverage_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('available', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
