# Generated by Django 4.2.23 on 2025-08-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('beverage_id', models.AutoField(primary_key=True, serialize=False)),
                ('beverage_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('beverage_category', models.IntegerField(choices=[(0, 'Smoothie Blends'), (1, 'Shake Varieties'), (2, 'New')], default=2)),
                ('available', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-available'],
            },
        ),
        migrations.DeleteModel(
            name='Milkshake',
        ),
        migrations.DeleteModel(
            name='Smoothie',
        ),
    ]
